//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.PrintCardServiceSOAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrintCardServiceSOAP.IPrintCardService")]
    public interface IPrintCardService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintCardService/RechargeByUserId", ReplyAction="http://tempuri.org/IPrintCardService/RechargeByUserIdResponse")]
        int RechargeByUserId(int userId, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintCardService/RechargeByUserId", ReplyAction="http://tempuri.org/IPrintCardService/RechargeByUserIdResponse")]
        System.Threading.Tasks.Task<int> RechargeByUserIdAsync(int userId, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintCardService/RechargeByUserName", ReplyAction="http://tempuri.org/IPrintCardService/RechargeByUserNameResponse")]
        int RechargeByUserName(string username, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintCardService/RechargeByUserName", ReplyAction="http://tempuri.org/IPrintCardService/RechargeByUserNameResponse")]
        System.Threading.Tasks.Task<int> RechargeByUserNameAsync(string username, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintCardService/RechargePrinterQuota", ReplyAction="http://tempuri.org/IPrintCardService/RechargePrinterQuotaResponse")]
        int RechargePrinterQuota(int cardId, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintCardService/RechargePrinterQuota", ReplyAction="http://tempuri.org/IPrintCardService/RechargePrinterQuotaResponse")]
        System.Threading.Tasks.Task<int> RechargePrinterQuotaAsync(int cardId, double amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrintCardServiceChannel : GUI.PrintCardServiceSOAP.IPrintCardService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrintCardServiceClient : System.ServiceModel.ClientBase<GUI.PrintCardServiceSOAP.IPrintCardService>, GUI.PrintCardServiceSOAP.IPrintCardService {
        
        public PrintCardServiceClient() {
        }
        
        public PrintCardServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrintCardServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrintCardServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrintCardServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int RechargeByUserId(int userId, double amount) {
            return base.Channel.RechargeByUserId(userId, amount);
        }
        
        public System.Threading.Tasks.Task<int> RechargeByUserIdAsync(int userId, double amount) {
            return base.Channel.RechargeByUserIdAsync(userId, amount);
        }
        
        public int RechargeByUserName(string username, double amount) {
            return base.Channel.RechargeByUserName(username, amount);
        }
        
        public System.Threading.Tasks.Task<int> RechargeByUserNameAsync(string username, double amount) {
            return base.Channel.RechargeByUserNameAsync(username, amount);
        }
        
        public int RechargePrinterQuota(int cardId, double amount) {
            return base.Channel.RechargePrinterQuota(cardId, amount);
        }
        
        public System.Threading.Tasks.Task<int> RechargePrinterQuotaAsync(int cardId, double amount) {
            return base.Channel.RechargePrinterQuotaAsync(cardId, amount);
        }
    }
}
